### ISSUE TITLE
Make a Chemper conda package

### ISSUE THREAD

**Issue by bannanc** [MobleyLab/chemper#90]
I wanted to make sure this one was documented since our README has said "will be conda installable soon" for a year. 

I don't think I'll have time to address the not "long term" issues and get this done this week. I could try to make time for it in August after I'm not on vacation.

**Comment by j-wags** [comment]
This is on the roadmap for OpenFF, but it's behind a lot of other high priority tasks. At the moment it seems like it won't be too hard, since all of the dependencies are on conda-forge, so we could package it directly on there.

I'd appreciate feedback from the community on whether a Chemper conda package would be helpful, so we can prioritize rolling this out if so. Please comment here is that's of interest!

**Comment by bannanc** [comment]
Just for the record, I wrote this issue when I started ChemPer because making things conda installable was something we were "supposed" to do as a MolSSI package. I never felt like it was ready for production use so it was never a priority for me, hence the long term tag.

**Comment by jthorton** [comment]
I think I will need to use chemper as part of the bespokefit workflow and a conda package would be very helpful during the installation. From what I can tell the dependencies are minimal so I could look at putting this straight on conda-forge rather than omnia first @j-wags @bannanc ?

**Comment by j-wags** [comment]
I'm hoping to have this out this week, as well as a CMILES conda package!

**Comment by jthorton** [comment]
Awesome! tag me when you start the migration, happy to be a maintainer for both!

**Comment by bannanc** [comment]
Thanks @j-wags I'm happy to help if you need anything.

**Comment by mattwthompson** [comment]
In progress here: https://github.com/conda-forge/staged-recipes/pull/12128 and CMILES, since it was brought up here: https://github.com/conda-forge/staged-recipes/pull/12129. Both are passing CI but may require a few more iterations before going online if the reviewers find issues

**Comment by mattwthompson** [comment]
Looks like this was completed a while back
